---

- name: Add users
  hosts: all
  become: yes

  vars_files:
  - users_pass.yml

  tasks:
  - name: Add users
    user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512') }}"
      update_password: always
      comment: "{{ item.name | lower }}@example.com"
      state: present
      home: "/home/{{ item.name | lower }}"
    loop: "{{ users }}"
    no_log: true
      

  
