---
- name: playbook #1
  hosts: all
  become: yes
  tasks:
  - name: install Apache server
    yum:
      name: httpd
      state: present
  - name: start service httpd and ensure httpd is running
    service:
      name: httpd
      state: started
  - name: create index.html
    lineinfile:
      path: /var/www/html/index.html
      create: yes
      line: “Welcome to my web server”
      state: present
  - name: install firewalld
    yum:
      name: firewalld
      state: present
  - name: start service firewalld and ensure firewalld is running
    service:
      name: firewalld
      state: started
  - name: permit traffic on port 80/tcp
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
  - name: permit traffic on port 443/tcp
    firewalld:
      zone: public
      port: 443/tcp
      permanent: true
      state: enabled
